#=============================================================================
# Euler0525@SpaceVim-config
#=============================================================================

[options]
    # Themes 
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # true colors
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    
    # options for layers checkers 
    enbale_neomake = true
    enable_ale = false
    lint_on_the_fly = false
    
    # option for autocomplete 
    autocomplete_method = "coc"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'checkers'
show_cursor_error = true

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# Debug
[[layers]]
  name = "debug"

# C/C++
[[layers]]
name = "lang#c"
enable_clang_synax_hightlight = true
clang_executable = "clang"
[layer.clang_std]
c = "c11"
cpp = "c++1z"
objc = "c11"
objcpp = "c++1z"


# format
[[layers]]
  name = "format"


# Python
[[layers]]
  name = "lang#python"

